id: I6452A9A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T22:23:55+00:00'
last_modified: '2022-06-09T04:42:47.677597+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3393
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང། ཁྲིད་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4BCB:
      image_group_id: I1KG3463
      title: Volume 1 of shes rab kyi pha rol tu phyin pa 'bum pa dang/ nyi khri lnga
        stong pa dang/ khrid brgyad stong pa'i rgya cher bshad pa
      total_pages: 1521
      order: 1
      base_file: 4BCB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
