id: P007085
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3393
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང། ཁྲིད་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ
  author: ''
  volumes:
    6e19d0a8b6c24c3d91e72e3cf7b4ea21:
      image_group_id: I1KG3463
      title: ''
      volume_number: 1
      total_pages: 1521
ebook_metadata:
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང། ཁྲིད་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ
  author: ''
  sku: P007085
  cover: cover.jpg
  layers:
  - pagination
