id: opecha:P007085
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3393
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང། ཁྲིད་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ
  volume: ''
  author: ''
