id: P007085
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3393
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང། ཁྲིད་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ
  author: ''
  volumes:
    2395c053dbcf40d89a3e1d95b1c9f96e:
      image_group_id: I1KG3463
      title: Volume 1 of shes rab kyi pha rol tu phyin pa 'bum pa dang/ nyi khri lnga
        stong pa dang/ khrid brgyad stong pa'i rgya cher bshad pa
      volume_number: 1
      total_pages: 1521
      base_file: v001.txt
ebook_metadata:
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང། ཁྲིད་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ
  author: ''
  sku: P007085
  cover: cover.jpg
  layers:
  - pagination
